CREATE DATABASE megasoft;
CREATE TABLE worker (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(1000) NOT NULL CHECK (LENGTH(Name) >= 2 AND LENGTH(Name) <= 1000),
    Birthday DATE CHECK (YEAR(Birthday) > 1900),
    Level VARCHAR(20) NOT NULL CHECK (Level IN ('Trainee', 'Junior', 'Middle', 'Senior')),
    Salary INT CHECK (Salary >= 100 AND Salary <= 100000)
);


CREATE TABLE client (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(1000) NOT NULL CHECK (LENGTH(Name) >= 2 AND LENGTH(Name) <= 1000)
);

CREATE TABLE project (
    ID INT PRIMARY KEY AUTO_INCREMENT,
	CLIENT_ID INT,
	START_DATE DATE,
	FINISH_DATE DATE
);

CREATE TABLE project_worker (
 PROJECT_ID INT,
    WORKER_ID INT,
    PRIMARY KEY (PROJECT_ID, WORKER_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES project(id),
    FOREIGN KEY (WORKER_ID) REFERENCES worker(id)
);



